# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('helper', django.db.models.manager.Manager()),
            ],
        ),
    ]
