# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20171116_0039'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
